name: maydan
description:  "This App create by Flutter version 3.24.0 ."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  get: ^4.6.6
#  awesome_dialog: ^3.3.0
  logger: ^2.4.0
  universal_platform: ^1.1.0
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/